"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var darken_1 = __importDefault(require("polished/lib/color/darken"));
var lighten_1 = __importDefault(require("polished/lib/color/lighten"));
var colors_1 = require("../utils/colors");
exports.Button = styled_components_1.css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  border: none;\n  border-radius: .375rem;\n  cursor: pointer;\n  outline: 0;\n  font-family: Montserrat, sans-serif;\n  color: ", ";\n  background: ", ";\n  text-decoration: none;\n  text-align: center;\n  white-space: nowrap;\n\n  transition-property: background-color,border-color,color,fill,stroke,opacity,box-shadow,transform;\n  transition-timing-function: cubic-bezier(.4,0,.2,1);\n  transition-duration: .15s;\n  padding-left: 1.5rem;\n  padding-right: 1.5rem;\n  padding-top: .75rem;\n  padding-bottom: .75rem;\n  line-height: 1.5rem;\n  font-weight: 500;\n\n  &:focus {\n    outline: 0;\n    box-shadow: 0 0 0 3px rgb(180,198,252);\n    border-color: rgb(81,69,205);\n  }\n\n  &:hover {\n    cursor: pointer;\n    background: ", ";\n    color: ", ";\n  }\n\n  &:active {\n    outline: 0;\n    background: ", ";\n    transform: scale(.99);\n  }\n"], ["\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  border: none;\n  border-radius: .375rem;\n  cursor: pointer;\n  outline: 0;\n  font-family: Montserrat, sans-serif;\n  color: ", ";\n  background: ", ";\n  text-decoration: none;\n  text-align: center;\n  white-space: nowrap;\n\n  transition-property: background-color,border-color,color,fill,stroke,opacity,box-shadow,transform;\n  transition-timing-function: cubic-bezier(.4,0,.2,1);\n  transition-duration: .15s;\n  padding-left: 1.5rem;\n  padding-right: 1.5rem;\n  padding-top: .75rem;\n  padding-bottom: .75rem;\n  line-height: 1.5rem;\n  font-weight: 500;\n\n  &:focus {\n    outline: 0;\n    box-shadow: 0 0 0 3px rgb(180,198,252);\n    border-color: rgb(81,69,205);\n  }\n\n  &:hover {\n    cursor: pointer;\n    background: ", ";\n    color: ", ";\n  }\n\n  &:active {\n    outline: 0;\n    background: ", ";\n    transform: scale(.99);\n  }\n"])), function (p) { return p.color ? p.color : colors_1.white; }, function (p) { return p.background ? p.background : colors_1.green600; }, function (p) { return p.background ? lighten_1.default(0.1, p.background) : colors_1.green400; }, function (p) { return p.color && p.background === colors_1.white ? colors_1.gray600 : p.color ? lighten_1.default(0.1, p.color) : colors_1.white; }, function (p) { return p.background ? darken_1.default(0.05, p.background) : colors_1.green700; });
exports.SidewaysShake = styled_components_1.keyframes(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  0% { transform: translate3d(0px, 0, 0) }\n  50% { transform: translate3d(5px, 0, 0) }\n  100% { transform: translate3d(0px, 0, 0) }\n"], ["\n  0% { transform: translate3d(0px, 0, 0) }\n  50% { transform: translate3d(5px, 0, 0) }\n  100% { transform: translate3d(0px, 0, 0) }\n"])));
var templateObject_1, templateObject_2;
//# sourceMappingURL=Button.js.map