FROM node:16-buster-slim as install

WORKDIR /install
COPY package.json .
COPY packages/types ./packages/types
COPY packages/shared-server ./packages/shared-server
COPY packages/express ./packages/express

RUN yarn

FROM node:16-buster-slim as build
WORKDIR /build

COPY --from=install /install .

RUN npm run build:types
RUN npm run build:shared-server
RUN npm run build:express

FROM node:16-buster-slim

COPY --from=build /build .

EXPOSE 8080

CMD ["npm", "run", "express"]